import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { PATHS } from '@/config/paths';
import taskOneChart from '@/assets/images/writingques.png';
import styles from './IeltsWritingTestPage.module.css';

const TASK = {
    time: 'Khoảng 20 phút',
    minimum: 150,
    prompt: 'The charts below show the percentage of water used for different agricultural products and the percentage of income generated by those products in one country.',
    instruction: 'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
} as const;

const formatTime = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`;
const countWords = (value: string) => value.trim() ? value.trim().split(/\s+/).length : 0;

const IeltsWritingTestPage = () => {
    const navigate = useNavigate();
    const { testId = 'cam-20-writing-1' } = useParams();
    const storageKey = `ielts-writing-draft:${testId}`;
    const [essay, setEssay] = useState(() => {
        const saved = window.localStorage.getItem(storageKey);
        if (!saved) return '';

        try {
            const parsed = JSON.parse(saved) as string | Record<string, string>;
            if (typeof parsed === 'string') return parsed;
            return parsed['1'] ?? '';
        } catch {
            return saved;
        }
    });
    const [remainingSeconds, setRemainingSeconds] = useState(20 * 60);
    const [saveState, setSaveState] = useState<'saved' | 'saving'>('saved');
    const [showSubmitDialog, setShowSubmitDialog] = useState(false);

    const words = countWords(essay);

    useEffect(() => {
        const timer = window.setInterval(() => setRemainingSeconds((current) => Math.max(0, current - 1)), 1000);
        return () => window.clearInterval(timer);
    }, []);

    useEffect(() => {
        const saveTimer = window.setTimeout(() => {
            window.localStorage.setItem(storageKey, JSON.stringify(essay));
            setSaveState('saved');
        }, 450);
        return () => window.clearTimeout(saveTimer);
    }, [essay, storageKey]);

    const updateEssay = (value: string) => {
        setSaveState('saving');
        setEssay(value);
    };

    const submit = () => {
        window.localStorage.removeItem(storageKey);
        setShowSubmitDialog(false);
        toast.success('Bài Writing đã được ghi nhận.');
        navigate(PATHS.DASHBOARD.IELTS_SKILL('writing'));
    };

    return (
        <main className={styles.examPage}>
            <header className={styles.topBar}>
                <div className={styles.testTitle}>
                    <span>IELTS Academic Writing</span>
                    <strong>{testId.replace(/-/g, ' ')}</strong>
                </div>
                <div className={styles.timer} aria-label="Thời gian còn lại"><span aria-hidden="true">◷</span>{formatTime(remainingSeconds)}</div>
                <div className={styles.headerActions}>
                    <button type="button" className={styles.exitButton} onClick={() => navigate(PATHS.DASHBOARD.IELTS_SKILL('writing'))}>Thoát</button>
                    <button type="button" className={styles.submitButton} onClick={() => setShowSubmitDialog(true)}>Nộp bài</button>
                </div>
            </header>

            <div className={styles.workspace}>
                <section className={styles.promptPane}>
                    <div className={styles.promptHeader}>
                        <span>Academic Writing</span>
                        <strong>{TASK.time}</strong>
                    </div>
                    <div className={styles.promptContent}>
                        <p>You should spend about 20 minutes on this task.</p>
                        <h1>{TASK.prompt}</h1>
                        <figure className={styles.chartFigure}>
                            <img src={taskOneChart} alt="Hai biểu đồ tròn về lượng nước sử dụng và thu nhập từ sản phẩm nông nghiệp" />
                        </figure>
                        <p className={styles.instruction}>{TASK.instruction}</p>
                        <p>Write at least <strong>{TASK.minimum} words</strong>.</p>
                    </div>
                </section>

                <section className={styles.editorPane}>
                    <div className={styles.editorHeader}>
                        <div><span>Bài viết của bạn</span></div>
                        <span className={styles.saveStatus}>{saveState === 'saving' ? 'Đang lưu…' : '✓ Đã lưu'}</span>
                    </div>
                    <textarea
                        value={essay}
                        onChange={(event) => updateEssay(event.target.value)}
                        placeholder="Bắt đầu viết câu trả lời tại đây…"
                        spellCheck
                        aria-label="Bài viết IELTS Writing"
                    />
                    <footer className={styles.editorFooter}>
                        <span className={words >= TASK.minimum ? styles.wordCountDone : styles.wordCount}>
                            <strong>{words}</strong> từ
                        </span>
                        <span>Mục tiêu tối thiểu: {TASK.minimum} từ</span>
                    </footer>
                </section>

                <aside className={styles.progressPanel}>
                    <div className={styles.progressHeading}><span>Tiến độ bài làm</span><strong>{words} từ</strong></div>
                    <div className={styles.progressCard}>
                        <span><strong>Writing</strong><small>{words} / {TASK.minimum} từ</small></span>
                        <i><b style={{ width: `${Math.min(100, (words / TASK.minimum) * 100)}%` }} /></i>
                    </div>
                    <div className={styles.tipCard}>
                        <span>Gợi ý</span>
                        <p>Dành vài phút để xác định đặc điểm nổi bật, sau đó nhóm và so sánh các số liệu quan trọng.</p>
                    </div>
                    <button type="button" className={styles.mobileSubmit} onClick={() => setShowSubmitDialog(true)}>Nộp bài</button>
                </aside>
            </div>

            {showSubmitDialog && (
                <div className={styles.modalBackdrop} role="presentation" onMouseDown={() => setShowSubmitDialog(false)}>
                    <section className={styles.submitDialog} role="dialog" aria-modal="true" aria-labelledby="writing-submit-title" onMouseDown={(event) => event.stopPropagation()}>
                        <span className={styles.dialogIcon}>✓</span>
                        <h2 id="writing-submit-title">Xác nhận nộp bài?</h2>
                        <p>Bài viết có <strong>{words} từ</strong>. Sau khi nộp, bạn sẽ không thể chỉnh sửa bài viết.</p>
                        {words < TASK.minimum && <div className={styles.warning}>Bài viết chưa đạt số từ tối thiểu.</div>}
                        <div className={styles.dialogActions}>
                            <button type="button" onClick={() => setShowSubmitDialog(false)}>Tiếp tục viết</button>
                            <button type="button" className={styles.confirmSubmit} onClick={submit}>Nộp bài ngay</button>
                        </div>
                    </section>
                </div>
            )}
        </main>
    );
};

export default IeltsWritingTestPage;
