export const PATHS = {
    HOME: '/',
    COURSE_DETAIL: (slug: string) => `/dashboard/course/${encodeURIComponent(slug)}`,
    LESSON_PLAYER: (lessonId: string) => `/dashboard/learning/lessons/${lessonId}`,
    MARKETING: {
        HOME: '/marketing',
    },
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        OTP: '/auth/otp',
        SUCCESS: '/auth/success',
        FORGOT_PASSWORD: '/auth/forgot-password',
    },
    DASHBOARD: {
        ROOT: '/dashboard',
        HOME: '/dashboard',
        RESULT: '/dashboard/result',
        WRITING: '/dashboard/writing',
        SPEAKING: '/dashboard/speaking',
        LEARNING: '/dashboard/learning',
        AI_VOICE: '/dashboard/ai-voice',
        ROADMAP: '/dashboard/roadmap',
        RECOMMEND_COURSE: '/dashboard/reccourse',
        ALL_COURSES: '/dashboard/courses',
        IELTS_PRACTICE: '/dashboard/ielts-practice',
        IELTS_SKILL: (skill: string) => `/dashboard/ielts-practice/${encodeURIComponent(skill)}`,
        IELTS_LISTENING_TEST: (testId: string) => `/dashboard/ielts-practice/listening/${encodeURIComponent(testId)}`,
        IELTS_READING_TEST: (testId: string) => `/dashboard/ielts-practice/reading/${encodeURIComponent(testId)}`,
        IELTS_WRITING_TEST: (testId: string) => `/dashboard/ielts-practice/writing/${encodeURIComponent(testId)}`,
        PROFILE: '/dashboard/profile',
        GOAL_SELECTION: '/dashboard/goal-selection',
        LANGUAGE_SELECTION: '/dashboard/language-selection',
        LEVEL_SELECTION: '/dashboard/level-selection',
        PLACEMENT_TEST: {
            ROOT:      '/dashboard/placement-test',
            INTRO:     '/dashboard/placement-test/intro',
            LISTENING: '/dashboard/placement-test/lr',
            WRITING:   '/dashboard/placement-test/writing',
            SPEAKING:  '/dashboard/placement-test/speaking',
            READING:   '/dashboard/placement-test/toeic/reading',
            RESULT:    '/dashboard/placement-test/result',
        },
    }
} as const;
